version: "3"
services:

  postgres: 
    image: postgres:latest
    ports:
      - 54320:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    networks:
      - the-square-network
    environment:
      -POSTGRES_PASSWORD: docker
  
  adminer:
    container_name: p2pe_adminer
    image: adminer
    restart: always
    ports:
        - 8080:8080
    networks:
      - the-square-network

  express:
    image: node:latest
    working_dir: /usr/src/app/P2PE
    ports:
      - "3001:3001"
    expose:
      - "3001"
    links:
      - "postgres:postgres"
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app/P2PE
    command: bash -c "npm i && node index.js"
    networks:
      - the-square-network
networks:
  the-square-network: